using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Content.Client.Materials.UI;

namespace Content.Client._Sunrise.Factory;

[GenerateTypedNameReferences]
public sealed partial class FactoryMaterialStorageWindow : DefaultWindow
{
    public FactoryMaterialStorageWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetOwner(EntityUid owner)
    {
        MaterialsList.SetOwner(owner);
    }
} 